HAL_TIM_PWM_Start(SERVO_PWM_TIM, SERVO_PWM_CHANNEL1);
HAL_TIM_PWM_Start(SERVO_PWM_TIM, SERVO_PWM_CHANNEL2);
HAL_TIM_PWM_Start(SERVO_PWM_TIM, SERVO_PWM_CHANNEL3);
HAL_TIM_PWM_Start(SERVO_PWM_TIM, SERVO_PWM_CHANNEL4);
__HAL_TIM_SET_COMPARE(SERVO_PWM_TIM, SERVO_PWM_CHANNEL1, 0);
__HAL_TIM_SET_COMPARE(SERVO_PWM_TIM, SERVO_PWM_CHANNEL2, 500);
__HAL_TIM_SET_COMPARE(SERVO_PWM_TIM, SERVO_PWM_CHANNEL3, 1000);
__HAL_TIM_SET_COMPARE(SERVO_PWM_TIM, SERVO_PWM_CHANNEL4, 1500);


#define SERVO_PWM_TIM &htim8
#define SERVO_PWM_CHANNEL1 TIM_CHANNEL_1
#define SERVO_PWM_CHANNEL2  TIM_CHANNEL_2
#define SERVO_PWM_CHANNEL3 TIM_CHANNEL_3
#define SERVO_PWM_CHANNEL4 TIM_CHANNEL_4

        __HAL_TIM_SET_COMPARE(SERVO_PWM_TIM, SERVO_PWM_CHANNEL1, 500+yaw*2000.0/180.0);
    		__HAL_TIM_SET_COMPARE(SERVO_PWM_TIM, SERVO_PWM_CHANNEL2, 500+yaw*4000.0/180.0);
            